# Generated by Django 3.0.2 on 2020-02-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20200203_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Publication date',
            new_name='art_date',
        ),
    ]
