# Generated by Django 3.0.2 on 2020-02-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20200203_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='art_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='art_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='art_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='art_title',
            new_name='title',
        ),
    ]
