# Generated by Django 3.0.2 on 2020-03-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_auto_20200203_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='curriculum',
            field=models.ImageField(upload_to=''),
        ),
    ]
