# Generated by Django 3.0.2 on 2020-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_auto_20200301_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='lang',
            field=models.CharField(default='english', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
